/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;
import edu.au.cc.gallery.tools.UserAdmin;

public class App {

    public static void main(String[] args) throws Exception {
	    UserAdmin.main();
    }
}
